### PR TITLE
FrontPage UI Improved 

### LINKED ISSUE #70: [Enhancement] : UI can be Improved in this Section
Following Improvement Can be done in this section :

**Text Contrast:** Make the title and subtitle stand out more against the background by using darker colors or adding shadows.

**Font Consistency:** Use a solid colour for the title instead of a gradient for better readability.

**Spacing:** Reduce space between the title and subtitle for a tighter layout.

**Background Overlay:** Add a dark overlay behind the text to improve visibility.

**Animation:** Consider adding subtle animations to the title for a more engaging look.

**Branding:** Include a logo or brand icon for identity.

**Call to Action:** Add a button (e.g., "Start Listening Now") to prompt user interaction.

**Visual Element:** Incorporate a small 3D object to enhance the visual appeal.

image

### PR DESCRIPTION
**Pull request by anuj846k**
Fixes #70 
**Changes Made**

1. I have created a Card grid view and added some shadows and better readability of text and it is responsive for mobiles also 
_[Image of 1 changes made]_ 
image

2. Replace text based play and pause in the navbar with play and pause react icon and shifted it to bottom right 
_[Image of 2 changes made]_ 
image
image

### CODE REVIEW

**Comment by AryanNanda17** [comment]
Screenshot 2024-10-16 at 9 32 21 PM
What is learn more here? It is useless. 
Screenshot 2024-10-16 at 9 32 43 PM
Why did you add these buttons?

**Comment by AryanNanda17** [comment]
The button looks good to me. You can remove the "click to play" text and just display the play button. Additionally, the play button should be activated by pressing the space key as well.

**Comment by anuj846k** [comment]
image

**Comment by ParamThakkar123** [comment]
@anuj846k any updates ??

**Comment by anuj846k** [comment]
> @anuj846k any updates ??

I have already updated the pull request 1 day ago commit id 281f9220182e7e3ae3b865a0747efb5c6e55e4d5

**Comment by ParamThakkar123** [comment]
> > @anuj846k any updates ??
> 
> I have already updated the pull request 1 day ago commit id [281f922](https://github.com/AryanNanda17/NonStop-Lofi-Vibe-Generator/commit/281f9220182e7e3ae3b865a0747efb5c6e55e4d5)

Okay, great. I am updating the codebase to add CI workflow for auto deployment

**Review by ParamThakkar123 — APPROVED** [review]

**Comment by ParamThakkar123** [comment]
Visual Element: Incorporate a small 3D object to enhance the visual appeal.

@anuj846k this part is yet to be done right ??

**Comment by anuj846k** [comment]
> Visual Element: Incorporate a small 3D object to enhance the visual appeal.
> 
> @anuj846k this part is yet to be done right ??

I tried but didn't find anything interesting also i have not worked with three js yet

**Pull request merged**
