### PR TITLE
Added About Page with proposed changes and Button on Navbar

### LINKED ISSUE #51: Building the about page UI
I noticed that the route for the About page is missing, which prevents access to it. We need to add the appropriate route to ensure the page is accessible and properly linked within the application.

### PR DESCRIPTION
**Pull request by shubhrad1**
Closes #51 

Made the proposed changes to About Page and added a button on the Navbar to navigate to About Page.

Due to a merge conflict, the previous PR was closed so I am creating a new PR with up to date changes.

### CODE REVIEW

**Comment by AryanNanda17** [comment]
Screenshot 2024-10-04 at 1 35 12 AM
Screenshot 2024-10-04 at 1 35 21 AM

**Comment by AryanNanda17** [comment]
LGTM!!
Great work @shubhrad1

**Comment by shubhrad1** [comment]
Thanks @AryanNanda17

**Review by ParamThakkar123 — APPROVED** [review]

**Comment by ParamThakkar123** [comment]
@shubhrad1 This looks great to me for now. There are further UI enhancements (because the information is just written down here) and ton of information is not exciting. We would want to make the UI of this page more better and immersive but I think that can be covered in another issue.

**Comment by ParamThakkar123** [comment]
This is ready to be merged

**Comment by ParamThakkar123** [comment]
Thanks for your contribution @shubhrad1 !

**Pull request merged**
