### PR TITLE
feature: Added About Page UI

### LINKED ISSUE #51: Building the about page UI
I noticed that the route for the About page is missing, which prevents access to it. We need to add the appropriate route to ensure the page is accessible and properly linked within the application.

### PR DESCRIPTION
**Pull request by shubhrad1**
Added UI for About Page with description about the Project, Features and Deep-Learning Models.
Closes #51

### CODE REVIEW

**Comment by AryanNanda17** [comment]
Hello @shubhrad1,
I checked your PR, but I don't see any "About" button to navigate to the About section. Where have you made the changes? How can I see them on the website?

**Comment by AryanNanda17** [comment]
If you can share Screenshot or video, that would be great.

**Comment by AryanNanda17** [comment]
@shubhrad1, 
Can you remove 
Screenshot 2024-10-03 at 8 23 26 AM
the above part and add 
Screenshot 2024-10-03 at 8 23 47 AM
the above one in the feature section. Remove the above one from deep learning models. 
Thanks

**Comment by AryanNanda17** [comment]
Also, please add a navbar icon `about` in the home page which links to this one.

**Comment by ParamThakkar123** [comment]
@shubhrad1 music visualization won't be a part of deep learning models, it should be a feature

**Pull request closed without merging**
