### PR TITLE
Fix: Dynamic navbar

### LINKED ISSUE #60: Need for Dynamic Navbar
Currently, the navbar on the homepage is not dynamic; decreasing the size of the window causes the navbar to disappear. The expected outcome is that decreasing the size of the window should collapse all the navbar elements into a hamburger symbol.

### PR DESCRIPTION
**Pull request by shubhrad1**
Fixes #60
The navbar is made dynamic with the tabs collapsing into a functional hamburger. 
Works for both Signed in user and default.

### CODE REVIEW

**Comment by AryanNanda17** [comment]
LGTM!

**Comment by ParamThakkar123** [comment]
@shubhrad1 Looks good.

**Comment by ParamThakkar123** [comment]
I am merging this

**Comment by ParamThakkar123** [comment]
@shubhrad1 Thanks for your another contribution !

**Pull request merged**
