### PR TITLE
Footer UI Enhancement

### LINKED ISSUE #46: Footer UI enhancement
Need some enhancement with the footer UI.

### PR DESCRIPTION
**Pull request by ChetanDayapule**
Fixes #46 

Screenshots:
image

image

image

### CODE REVIEW

**Comment by ParamThakkar123** [comment]
@ChetanDayapule The footer is not visible

**Comment by AryanNanda17** [comment]
@ChetanDayapule, any updates?

**Comment by ChetanDayapule** [comment]
I'm not feeling well, will check n update in a couple of days. Thank you!

**Comment by AryanNanda17** [comment]
Alright!
Take care.

**Comment by ChetanDayapule** [comment]
@AryanNanda17 Footer was not visible due to screen resolution. It is fixed now, so please consider it for (re)review and approval. Thank you.

**Comment by AryanNanda17** [comment]
Screenshot 2024-10-10 at 6 56 13 PM

@ChetanDayapule, please remove the unnecessary white space and keep only the GitHub link, removing all other social media links. Also, remove the terms of use and privacy policy. Add the creators' names—Aryan Nanda, Param Thakkar, Kamakshi Ramamurthy, and Mohammed Bhadsorwala—in the middle.

**Comment by AryanNanda17** [comment]
@ChetanDayapule, any updates?

**Comment by AryanNanda17** [comment]
@ChetanDayapule, are you working on the requested changes?

**Pull request closed without merging**
