### PR TITLE
Optimise performance of components

### PR DESCRIPTION
**Pull request by nikkuv**
Tried lazy loading expensive routes that were taking more time to load ( found out from react profiler )
Tried to reduce re-renders for the `/experience` components by adding useCallback. 
Formated the code a bit. 
.
.
.
Will try code splitting for front page component to see if it helps in performance optimization.

### CODE REVIEW

**Comment by ParamThakkar123** [comment]
This works great so far!

**Comment by ParamThakkar123** [comment]
Code splitting would help to some extent. You can definitely try that

**Comment by AryanNanda17** [comment]
@nikkuv, any updates on code splitting?

**Comment by nikkuv** [comment]
@AryanNanda17 hey I tried code splitting but it was breaking things...I wasn't able to find out how it is happening so not doing that. Sorry.

**Comment by ParamThakkar123** [comment]
> @AryanNanda17 hey I tried code splitting but it was breaking things...I wasn't able to find out how it is happening so not doing that. Sorry.

No problem. We can address that later. We will review and merge this pr soon.

**Comment by ParamThakkar123** [comment]
The code is written really well. But the animations on the page are really heavy which caused only a slight optimization in performance than the previous. We can rather move forward to merging this for now and explore more possible approaches to optimize this and make its performance better

**Comment by ParamThakkar123** [comment]
Thanks for your contribution @nikkuv !

**Comment by ParamThakkar123** [comment]
Maybe we can try code splitting in the future.

**Pull request merged**
