### PR TITLE
enhance ui of about page

### PR DESCRIPTION
**Pull request by matinshaikh31**
#78 
i change the ui design of about page to make it look more attractive
i add icons change font size of headings and paragraph

### CODE REVIEW

**Comment by AryanNanda17** [comment]
Please share screenshots here.

**Comment by matinshaikh31** [comment]
This is Old Ui
image
image


This is New Ui
image
image

**Comment by AryanNanda17** [comment]
@matinshaikh31 , it would be awesome if you would star this repo.

**Comment by AryanNanda17** [comment]
> This is New Ui

Awesome!
@ParamThakkar123, what do you think.

**Comment by ParamThakkar123** [comment]
This looks great!!

**Comment by matinshaikh31** [comment]
so are you merge this changes ?

**Pull request merged**
