### PR TITLE
feat: Add page transition

### PR DESCRIPTION
**Pull request by RNAdvani**

### CODE REVIEW

**Comment by AryanNanda17** [comment]
Hello @RNAdvani, 
Could you please update the transition from current one to something like what this site has https://dennissnellenberg.com/work. 
Please align it more with our site's theme

**Comment by RNAdvani** [comment]
is there any colour preference you wanna give me?

**Comment by AryanNanda17** [comment]
see the theme of the site... black and purplish

**Comment by RNAdvani** [comment]
do check

**Comment by AryanNanda17** [comment]
There are issues:-
- Consistency issues:- Make sure animation on every page transition should be like this:- incoming pink shade with text which remains in the middle and then outgoing pink shade and text goes along with it as the pink shade reaches the middle portion. Currently, the transition on every page is different. 
- In the music experience page -> music experience has stopped working due to transition. Make sure it doesn't affect working on the website. 
- your PR shows that you have added music as well... but it is already there on the website. Please make sure to pull all the changes and commit only relevant files.

**Comment by AryanNanda17** [comment]
theme of page transition is good rn... Good work on that.

**Comment by ParamThakkar123** [comment]
@AryanNanda17 is this transition working as expected ??

**Comment by AryanNanda17** [comment]
No, @ParamThakkar123 there are some issues. I have mentioned above.

**Comment by ParamThakkar123** [comment]
@RNAdvani any progress so far ??

**Comment by RNAdvani** [comment]
yes i am working on it the reason of this issue is that each page has a motion div which abruptly forces that transition, I'll c what i can do

**Comment by AryanNanda17** [comment]
@RNAdvani, updates?

**Comment by RNAdvani** [comment]
yes i am resolving it, i'll push tonight

**Comment by RNAdvani** [comment]
mostly i would have to remove all animations from other pages to make the transition work as it is interrupting with the transition, can i do so?

**Comment by ParamThakkar123** [comment]
> mostly i would have to remove all animations from other pages to make the transition work as it is interrupting with the transition, can i do so?

There are no other animations on pages I think except page and word animations. Try without removing the existing animations. That's recommended.

**Comment by ParamThakkar123** [comment]
Also this PR has some conflicts to resolve

**Comment by AryanNanda17** [comment]
@RNAdvani Updates?

**Pull request closed without merging**
