### PR TITLE
feat: add page transition

### LINKED ISSUE #50: Transition between pages
Our pages currently transition abruptly, which impacts the user experience. Adding smooth page transitions would improve the interface's flow and make navigation more seamless.

### PR DESCRIPTION
**Pull request by Badra00**
fixes #50

### CODE REVIEW

**Comment by Badra00** [comment]
I made a first version of the transition let me know if you want to change something

**Comment by ParamThakkar123** [comment]
@Badra00 This works but only for some pages. Also the transition occurs but not smoothly, there's some lagging when we go from one page to the another.

**Comment by AryanNanda17** [comment]
@Badra00, any updates?

**Comment by Badra00** [comment]
Hey
I will have a look later and try to find a solution

Cordialement,
Badradine Boulahia

**Comment by AryanNanda17** [comment]
@Badra00, any updates?

**Comment by AryanNanda17** [comment]
This issue has been inactive for a week! @Badra00, are you still working on getting this done?

**Pull request closed without merging**
